version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - typecheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
