repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint (task lint:local)
        entry: task lint:local
        language: system
        pass_filenames: false
        always_run: true
