version: '3'

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  dagger:login:
    desc: Login to Dagger Cloud organization
    cmds:
      - dagger login $DAGGER_ORG_ID

  init:local:
    internal: true
    cmds:
      - go mod tidy

  init:
    desc: Prepare Go module dependencies (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task init:local

  build:local:
    internal: true
    cmds:
      - go build -v ./...

  build:
    desc: Build all Go packages (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task build:local

  test:local:
    internal: true
    cmds:
      - go test ./...

  test:
    desc: Run unit and integration tests (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task test:local

  test:ci:local:
    internal: true
    env:
      CI: "true"
    cmds:
      - go test ./...

  test:ci:
    desc: Run tests in CI mode (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task test:ci:local

  lint:local:
    internal: true
    cmds:
      - golangci-lint run --config=.golangci.yml

  lint:
    desc: Run golangci-lint with repository configuration (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task lint:local

  fmt:lint:local:
    internal: true
    cmds:
      - golangci-lint fmt --config=.golangci.yml

  fmt:lint:
    desc: Apply golangci-lint formatters (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task fmt:lint:local

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit install --hook-type commit-msg

  pre-commit:run:
    desc: Run all pre-commit hooks
    cmds:
      - pre-commit run --all-files

  pact:install:local:
    internal: true
    cmds:
      - mkdir -p .pact/lib
      - go run github.com/pact-foundation/pact-go/v2@v2.4.2 install --force --libDir .pact/lib

  pact:install:
    desc: Install Pact FFI runtime into local repo folder (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task pact:install:local

  test:pact:local:
    internal: true
    deps:
      - pact:install:local
    cmds:
      - |
        set -eu
        lib_file="$(find .pact/lib -maxdepth 1 -type f \( -name 'libpact_ffi.dylib' -o -name 'libpact_ffi.so' -o -name 'libpact_ffi.so.*' \) | head -n 1)"
        if [ -z "$lib_file" ]; then
          echo "libpact_ffi was not found in .pact/lib"
          ls -la .pact/lib || true
          exit 1
        fi

        lib_base="$(basename "$lib_file")"
        rm -f "/tmp/$lib_base"
        cp "$lib_file" "/tmp/$lib_base"

        case "$lib_base" in
          *.dylib)
            export DYLD_LIBRARY_PATH="/tmp:${PWD}/.pact/lib:${DYLD_LIBRARY_PATH:-}"
            ;;
          *.so)
            export LD_LIBRARY_PATH="/tmp:${PWD}/.pact/lib:${LD_LIBRARY_PATH:-}"
            ;;
          *.so.*)
            rm -f /tmp/libpact_ffi.so
            ln -sf "/tmp/$lib_base" /tmp/libpact_ffi.so
            export LD_LIBRARY_PATH="/tmp:${PWD}/.pact/lib:${LD_LIBRARY_PATH:-}"
            ;;
        esac

        go test -tags pact ./...

  test:pact:
    desc: Run pact-tagged tests (via Dagger)
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task test:pact:local

  ci:local:
    internal: true
    cmds:
      - task: init:local
      - task: lint:local
      - task: build:local
      - task: test:ci:local

  ci:
    desc: Full CI pipeline (init, lint, build, tests) via Dagger
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task ci:local

  pact:ci:
    desc: Run Pact pipeline in Dagger
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task test:pact:local

  release:local:
    internal: true
    cmds:
      - go build -v ./...

  release:
    desc: Build release artifacts via Dagger
    deps:
      - dagger:login
    cmds:
      - dagger run -- mise exec -- task release:local

  vagrant:start:
    desc: Start Vagrant VM
    cmds:
      - vagrant up

  vagrant:stop:
    desc: Stop Vagrant VM
    cmds:
      - vagrant stop

  vagrant:destroy:
    desc: Destroy Vagrant VM
    cmds:
      - vagrant destroy -f